services:
    cartListener:
        class: ElectroAtoui\FrontendBundle\Events\CartListener
        arguments: [@service_container,@session]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    SecurityListener:
        class: ElectroAtoui\FrontendBundle\Events\SecurityListener
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    PasswordResettingListener:
        class: ElectroAtoui\FrontendBundle\Events\PasswordResettingListener
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }
    frontend.user_provider.email:
        class: ElectroAtoui\FrontendBundle\Events\EmailProvider
        public: false
        arguments: [@fos_user.user_manager]
    frontend.registration.form.type:
        class: ElectroAtoui\FrontendBundle\Form\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: user_registration }
    FactureToPdf:
      class: ElectroAtoui\FrontendBundle\Services\GenerateFacture
      arguments: [@service_container]
