_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

_main:
    resource: routing.yml

backend:
    resource: "@BackendBundle/Resources/config/routing.yml"
    prefix:   /admin

frontend:
    resource: "@FrontendBundle/Resources/config/routing.yml"
    prefix:   /

api:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /api
