security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    providers:
        fos_userbundle:
            id: frontend.user_provider.email
    acl:
        connection: default
    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                remember_me: true
            remember_me:
                key:      %secret%
                lifetime: 345600
                path:     /
            logout:       true
            anonymous:    true
        login:
            pattern:   ^/(login$|register|resetting)
            anonymous: true
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
    access_control:
        - { path: ^/(login$|register|resetting), role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/my_account, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
