<?php

namespace Proxies\__CG__\ElectroAtoui\CoreBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Order extends \ElectroAtoui\CoreBundle\Entity\Order implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', '' . "\0" . 'ElectroAtoui\\CoreBundle\\Entity\\Order' . "\0" . 'user', '' . "\0" . 'ElectroAtoui\\CoreBundle\\Entity\\Order' . "\0" . 'shipping_address', '' . "\0" . 'ElectroAtoui\\CoreBundle\\Entity\\Order' . "\0" . 'total', '' . "\0" . 'ElectroAtoui\\CoreBundle\\Entity\\Order' . "\0" . 'status', '' . "\0" . 'ElectroAtoui\\CoreBundle\\Entity\\Order' . "\0" . 'is_valid', '' . "\0" . 'ElectroAtoui\\CoreBundle\\Entity\\Order' . "\0" . 'createdAt', '' . "\0" . 'ElectroAtoui\\CoreBundle\\Entity\\Order' . "\0" . 'reference', '' . "\0" . 'ElectroAtoui\\CoreBundle\\Entity\\Order' . "\0" . 'order_lines');
        }

        return array('__isInitialized__', 'id', '' . "\0" . 'ElectroAtoui\\CoreBundle\\Entity\\Order' . "\0" . 'user', '' . "\0" . 'ElectroAtoui\\CoreBundle\\Entity\\Order' . "\0" . 'shipping_address', '' . "\0" . 'ElectroAtoui\\CoreBundle\\Entity\\Order' . "\0" . 'total', '' . "\0" . 'ElectroAtoui\\CoreBundle\\Entity\\Order' . "\0" . 'status', '' . "\0" . 'ElectroAtoui\\CoreBundle\\Entity\\Order' . "\0" . 'is_valid', '' . "\0" . 'ElectroAtoui\\CoreBundle\\Entity\\Order' . "\0" . 'createdAt', '' . "\0" . 'ElectroAtoui\\CoreBundle\\Entity\\Order' . "\0" . 'reference', '' . "\0" . 'ElectroAtoui\\CoreBundle\\Entity\\Order' . "\0" . 'order_lines');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Order $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setReference($reference)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReference', array($reference));

        return parent::setReference($reference);
    }

    /**
     * {@inheritDoc}
     */
    public function getReference()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReference', array());

        return parent::getReference();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotal($total)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotal', array($total));

        return parent::setTotal($total);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotal', array());

        return parent::getTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingAddress($shipping_address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingAddress', array($shipping_address));

        return parent::setShippingAddress($shipping_address);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingAddress', array());

        return parent::getShippingAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsValid($is_valid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsValid', array($is_valid));

        return parent::setIsValid($is_valid);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsValid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsValid', array());

        return parent::getIsValid();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($created_at)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($created_at));

        return parent::setCreatedAt($created_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderLines()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderLines', array());

        return parent::getOrderLines();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrderLine(\ElectroAtoui\CoreBundle\Entity\OrderLine $order_line)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrderLine', array($order_line));

        return parent::addOrderLine($order_line);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrderLine(\ElectroAtoui\CoreBundle\Entity\OrderLine $order_line)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrderLine', array($order_line));

        return parent::removeOrderLine($order_line);
    }

}
