<?php

namespace ElectroAtoui\CoreBundle\Repository;

use Gedmo\Tree\Entity\Repository\NestedTreeRepository;


/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends NestedTreeRepository
{

    public function getChildrens($category_id)
    {
        $qb = $this->createQueryBuilder('c')
                ->Select('c')
                ->Where('c.parent = :parent_id')
                ->setParameter('parent_id', $category_id);
        return $qb->getQuery()->getResult();
    }


    public function getCategories()
    {
        $qb = $this->createQueryBuilder('c')
                ->Select('c')
                ->Where('c.parent is NULL');
        return $qb->getQuery()->getResult();
    }


    public function getTree()
    {
        $qb = $this->createQueryBuilder('node')
                ->Select('node')
                ->orderBy('node.root, node.lft', 'ASC');
        return $qb->getQuery()->getArrayResult();
    }


    public function getOrderCategories()
    {
        return $this->getEntityManager()->createQuery(
            'SELECT T, C FROM ElectroAtoui\CoreBundle\Entity\Category T
            LEFT JOIN T.childrens AS C
            WHERE T.parent IS NULL'
        )->getResult();
    }
}
